name: md_engine
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  qlevar_router: ^1.11.2
  mask_text_input_formatter: ^2.9.0
  lottie: ^2.7.0
  flutter_svg: ^2.0.10+1
  uuid: ^4.2.2
  intl: 0.18.1
  easy_mask: ^2.0.1
  auto_size_text: ^3.0.0
  infinite_scroll_pagination: ^4.0.0
  paged_datatable: ^1.4.4
  diacritic: ^0.1.5
  get_it: ^8.0.0
  device_info_plus: ^9.1.2
  package_info_plus: ^4.2.0
  rx_notifier: ^2.3.0
  dropdown_button2: ^2.3.9
  universal_platform: ^1.1.0
  collection: ^1.17.2
  json_store: ^2.0.1
  encrypt_env: ^1.1.0
  args: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

executables:
  md_engine: bin/md_engine.dart

flutter:
  assets:
   - lib/i18n/
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
